# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/product.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'proto/product.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/product.proto\x12\x07product\"E\n\x15SearchProductsRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x0e\n\x06offset\x18\x03 \x01(\x05\"Q\n\x16SearchProductsResponse\x12\"\n\x08products\x18\x01 \x03(\x0b\x32\x10.product.Product\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\"\'\n\x11GetProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\"F\n\x11\x41\x64\x64ProductRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\"(\n\x12\x41\x64\x64ProductResponse\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\"*\n\x14\x44\x65leteProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\"(\n\x15\x44\x65leteProductResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"H\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x32\xb6\x02\n\x0eProductService\x12:\n\nGetProduct\x12\x1a.product.GetProductRequest\x1a\x10.product.Product\x12Q\n\x0eSearchProducts\x12\x1e.product.SearchProductsRequest\x1a\x1f.product.SearchProductsResponse\x12\x45\n\nAddProduct\x12\x1a.product.AddProductRequest\x1a\x1b.product.AddProductResponse\x12N\n\rDeleteProduct\x12\x1d.product.DeleteProductRequest\x1a\x1e.product.DeleteProductResponseB\x0fZ\rproduct/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.product_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rproduct/proto'
  _globals['_SEARCHPRODUCTSREQUEST']._serialized_start=32
  _globals['_SEARCHPRODUCTSREQUEST']._serialized_end=101
  _globals['_SEARCHPRODUCTSRESPONSE']._serialized_start=103
  _globals['_SEARCHPRODUCTSRESPONSE']._serialized_end=184
  _globals['_GETPRODUCTREQUEST']._serialized_start=186
  _globals['_GETPRODUCTREQUEST']._serialized_end=225
  _globals['_ADDPRODUCTREQUEST']._serialized_start=227
  _globals['_ADDPRODUCTREQUEST']._serialized_end=297
  _globals['_ADDPRODUCTRESPONSE']._serialized_start=299
  _globals['_ADDPRODUCTRESPONSE']._serialized_end=339
  _globals['_DELETEPRODUCTREQUEST']._serialized_start=341
  _globals['_DELETEPRODUCTREQUEST']._serialized_end=383
  _globals['_DELETEPRODUCTRESPONSE']._serialized_start=385
  _globals['_DELETEPRODUCTRESPONSE']._serialized_end=425
  _globals['_PRODUCT']._serialized_start=427
  _globals['_PRODUCT']._serialized_end=499
  _globals['_PRODUCTSERVICE']._serialized_start=502
  _globals['_PRODUCTSERVICE']._serialized_end=812
# @@protoc_insertion_point(module_scope)
