name: Full Integration Tests

on: [push]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.3'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build product image
        run: docker build -f product/Dockerfile -t product-image:latest .

      - name: Build user-cart-order image
        run: docker build -f user-cart-order/Dockerfile -t user-cart-order-image:latest .

      - name: Build llm-service image
        run: docker build -f llm-service/Dockerfile -t llm-service-image:latest .

      - name: Run integration tests
        env:
          YANDEX_API_KEY: ${{ secrets.YANDEX_API_KEY }}
          YANDEX_FOLDER_ID: ${{ secrets.YANDEX_FOLDER_ID }}
        run: go test -v ./...
        working-directory: ./integration-test/integration
