name: Product CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'product/**'
      - 'schema-registry/proto/product.proto'
  pull_request:
    branches: [ main ]
    paths:
      - 'product/**'
      - 'schema-registry/proto/product.proto'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./user-cart-order/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/product:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/product:${{ github.sha }}
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/product:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/product:buildcache,mode=max